// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XBACKSUB_H
#define XBACKSUB_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbacksub_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
    u32 Crtl_bus_BaseAddress;
} XBacksub_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XBacksub;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBacksub_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBacksub_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBacksub_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBacksub_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBacksub_Initialize(XBacksub *InstancePtr, u16 DeviceId);
XBacksub_Config* XBacksub_LookupConfig(u16 DeviceId);
int XBacksub_CfgInitialize(XBacksub *InstancePtr, XBacksub_Config *ConfigPtr);
#else
int XBacksub_Initialize(XBacksub *InstancePtr, const char* InstanceName);
int XBacksub_Release(XBacksub *InstancePtr);
#endif

void XBacksub_Start(XBacksub *InstancePtr);
u32 XBacksub_IsDone(XBacksub *InstancePtr);
u32 XBacksub_IsIdle(XBacksub *InstancePtr);
u32 XBacksub_IsReady(XBacksub *InstancePtr);
void XBacksub_EnableAutoRestart(XBacksub *InstancePtr);
void XBacksub_DisableAutoRestart(XBacksub *InstancePtr);
u32 XBacksub_Get_return(XBacksub *InstancePtr);

void XBacksub_Set_frame_in(XBacksub *InstancePtr, u32 Data);
u32 XBacksub_Get_frame_in(XBacksub *InstancePtr);
void XBacksub_Set_frame_out(XBacksub *InstancePtr, u32 Data);
u32 XBacksub_Get_frame_out(XBacksub *InstancePtr);
void XBacksub_Set_init(XBacksub *InstancePtr, u32 Data);
u32 XBacksub_Get_init(XBacksub *InstancePtr);

void XBacksub_InterruptGlobalEnable(XBacksub *InstancePtr);
void XBacksub_InterruptGlobalDisable(XBacksub *InstancePtr);
void XBacksub_InterruptEnable(XBacksub *InstancePtr, u32 Mask);
void XBacksub_InterruptDisable(XBacksub *InstancePtr, u32 Mask);
void XBacksub_InterruptClear(XBacksub *InstancePtr, u32 Mask);
u32 XBacksub_InterruptGetEnabled(XBacksub *InstancePtr);
u32 XBacksub_InterruptGetStatus(XBacksub *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
