// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of frame_in
//        bit 31~0 - frame_in[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of frame_out
//        bit 31~0 - frame_out[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBACKSUB_AXILITES_ADDR_FRAME_IN_DATA  0x10
#define XBACKSUB_AXILITES_BITS_FRAME_IN_DATA  32
#define XBACKSUB_AXILITES_ADDR_FRAME_OUT_DATA 0x18
#define XBACKSUB_AXILITES_BITS_FRAME_OUT_DATA 32

// CRTL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of init
//        bit 0  - init[0] (Read/Write)
//        others - reserved
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBACKSUB_CRTL_BUS_ADDR_AP_CTRL   0x00
#define XBACKSUB_CRTL_BUS_ADDR_GIE       0x04
#define XBACKSUB_CRTL_BUS_ADDR_IER       0x08
#define XBACKSUB_CRTL_BUS_ADDR_ISR       0x0c
#define XBACKSUB_CRTL_BUS_ADDR_AP_RETURN 0x10
#define XBACKSUB_CRTL_BUS_BITS_AP_RETURN 32
#define XBACKSUB_CRTL_BUS_ADDR_INIT_DATA 0x18
#define XBACKSUB_CRTL_BUS_BITS_INIT_DATA 1

