// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbacksub.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBacksub_CfgInitialize(XBacksub *InstancePtr, XBacksub_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBacksub_Start(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBacksub_IsDone(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBacksub_IsIdle(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBacksub_IsReady(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBacksub_EnableAutoRestart(XBacksub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XBacksub_DisableAutoRestart(XBacksub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_CTRL, 0);
}

u32 XBacksub_Get_return(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_AP_RETURN);
    return Data;
}
void XBacksub_Set_init(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_INIT_DATA, Data);
}

u32 XBacksub_Get_init(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_INIT_DATA);
    return Data;
}

void XBacksub_Set_frame_in(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_IN_DATA, Data);
}

u32 XBacksub_Get_frame_in(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_IN_DATA);
    return Data;
}

void XBacksub_Set_frame_out(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_OUT_DATA, Data);
}

u32 XBacksub_Get_frame_out(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_OUT_DATA);
    return Data;
}

void XBacksub_InterruptGlobalEnable(XBacksub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_GIE, 1);
}

void XBacksub_InterruptGlobalDisable(XBacksub *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_GIE, 0);
}

void XBacksub_InterruptEnable(XBacksub *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_IER);
    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XBacksub_InterruptDisable(XBacksub *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_IER);
    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XBacksub_InterruptClear(XBacksub *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XBacksub_InterruptGetEnabled(XBacksub *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_IER);
}

u32 XBacksub_InterruptGetStatus(XBacksub *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_ISR);
}

